org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configureondemand=false
kotlin.code.style=official
# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true
# compileSdk 36 için AGP uyarısını bastır (gerekirse)
android.suppressUnsupportedCompileSdk=36
